lecture/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo/',include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
# have to create this urls.py file manually

from django.urls import path

from todo.views import index, detail, createlist, createitem,item,view

app_name='todo'
urlpatterns = [
    path('', index, name='index'),
    path('view/', view, name='view'),
    path('<int:list_id>/', detail, name='list_details'),
    path('createlist/', createlist, name='list_create'),
    path('createitem/', createitem, name='item_create'),
    path('<int:list_id>/<int:item_id>/',item,name='item_details'),
    path('<int:list_id>/createitem/',createitem,name='item_create')
]

todo/models.py
from django.db import models
import datetime
from django.db.utils import IntegrityError
import pytz
from django.utils.timezone import now

# Create your models here.

"""

List - eg. IMG TODO LIST, cad TODO list
Item - what task it is.

"""
# database model structure


# table
class TodoList(models.Model):
 
    list_name = models.CharField(max_length=100, unique=True, blank=True, null=True)

    def __str__(self):
        return f"{self.list_name}"

# table
class TodoItem(models.Model):
    now=datetime.datetime.now()
    title = models.CharField(max_length=100)
    checked = models.BooleanField(default=False)
    due_date= models.DateTimeField(default=now)
    
    # foreignkey 
    todo_list = models.ForeignKey(to=TodoList, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['title', 'todo_list'], name='name of constraint')
        ]

    def __str__(self):
        return f"{self.todo_list.list_name}: {self.title}"

todo/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,Http404
from django.template import loader
from django.db import IntegrityError
import datetime
import pytz
from django.core.exceptions import ValidationError

from .models import TodoList
from .models import TodoItem

# Create your views here.

#->before template
# def index(request):
#     todolists = TodoList.objects.all()
#     list_items=TodoItem.objects.all()

#     output=', '.join(item.title for item in list_items) 
#     return HttpResponse(output)

# after template
def index(request):
    """url:todo/ , Home page displays links to all lists"""

    todolists = TodoList.objects.all()
    todoitems = TodoItem.objects.all()
    # template = loader.get_template('todo/index.html')
    context = {
        'todolists': todolists,
        'todoitems': todoitems,
    }
    # return HttpResponse(template.render(context,request)) #this or->
    return render(request, 'todo/index.html',context)

def view(request):
    """displays all lists and items in todo app"""

    todolists = TodoList.objects.all()
    todoitems = TodoItem.objects.all()
    # template = loader.get_template('todo/index.html')
    context = {
        'todolists': todolists,
        'todoitems': todoitems,
    }

    # return HttpResponse(template.render(context,request)) #this or->
    return render(request, 'todo/view.html',context)

def createlist(request):
    """creates list"""

    if request.method == "GET":
        return render(request, 'todo/createlist.html')

    name = request.POST.get("name")
    if(name == ""):
        return HttpResponse("Error: Name cannot be blank")
    try:
        TodoList.objects.create(list_name=name)
        lists = TodoList.objects.all()
        context = {
            'todolists': lists,
        }
        return redirect("/todo/")
    except IntegrityError:
        return HttpResponse("Error: list name already exists")

def detail(request,list_id):
    """each list in detail -- updation and deletion"""

    if request.method == "GET":
        try:
            todolist=TodoList.objects.get(id=list_id)
        except:
            raise Http404("This List Does not exist")
        items_list=TodoItem.objects.filter(todo_list=todolist)
        context={
            'todolist':todolist,
            'items_list':items_list
        }
        return render(request, 'todo/detail.html',context)   
    
    if 'update' in request.POST:
        todolist_name = request.POST.get("name")
        if(todolist_name == ""):
            return HttpResponse("Error: Name cannot be blank")
        try:
            t=TodoList.objects.get(id=list_id)
            items_list=TodoItem.objects.filter(todo_list=t)

            todolist=request.POST.get("name")
            TodoList.objects.filter(id=list_id).update(list_name=todolist_name)
            todolists = TodoList.objects.all()
        except IntegrityError:
            return HttpResponse("Error: list name already exists")

    elif 'delete' in request.POST:
        try:
            t=TodoList.objects.get(id=list_id)
            t.delete()
        except:
            return Http404("This list does not exist")
        
    todolists = TodoList.objects.all()
    items = TodoItem.objects.all()
    context = {
        'todolists': todolists,
        'todoitems': items,
    }
    return redirect("/todo/")

def createitem(request,list_id=None):
    """creates item"""

    if request.method == "GET":
        lists = TodoList.objects.all()
        context = {
        'todolists': lists,
        'listid':list_id
        }
        return render(request, 'todo/createitem.html',context)

    todoitem=request.POST.get("item")
    if(todoitem==""):
        return HttpResponse("Error: List name cannot be blank")

    try: 
        todo_list = request.POST.get("todolist")
        try:
            t=TodoList.objects.get(id=todo_list)
        except:
            raise Http404("List id not found")

        todo_list=int(todo_list)
        check=bool(request.POST.get("check",False))
        time=request.POST.get("time")
        date=request.POST.get("date")
        if(time!=''):
            duetime=datetime.datetime.strptime(time,'%H:%M').time()
        else:
            duetime=datetime.datetime.now().strftime('%H:%M')
            duetime=datetime.datetime.strptime(duetime,'%H:%M').time()

        if(date!=''):
            duedate=datetime.datetime.strptime(date,'%Y-%m-%d').date()
        else:
            duedate=datetime.datetime.now().strftime('%Y-%m-%d')
            duedate=datetime.datetime.strptime(duedate,'%Y-%m-%d').date()

        due_date=datetime.datetime.combine(duedate,duetime)

        TodoItem.objects.create(title=todoitem,checked=check,due_date=due_date,todo_list=t)

        for obj in TodoItem.objects.filter(title=todoitem):
            print(obj.due_date)

        t=TodoList.objects.get(id=todo_list)
        items_list=TodoItem.objects.filter(todo_list=todo_list)
        context = {
            'todolist': t,
            'items_list':items_list,
        }
        return redirect("/todo/"+str(todo_list))
    except IntegrityError:
        return HttpResponse("Error: item name already exists under the selected list")

def item(request,list_id,item_id):
    """shows each item in detail -- updation and deletion"""
    
    if request.method == "GET":
        try:
            todolist = TodoList.objects.get(id=list_id)
        except:
            raise Http404("This List Does not exist")
        try:
            todoitem=TodoItem.objects.get(id=item_id)
        except:
            raise Http404("This Item Does not exist")
        lists = TodoList.objects.all()
        context = {
        'todolist': todolist,
        'todoitem': todoitem,
        'todolists':lists,
        }
        return render(request, 'todo/item.html',context)
    
    if 'update' in request.POST:
        try:
            todo_list = int(request.POST.get("todolist"))
            try:
                t=TodoList.objects.get(id=todo_list)
            except:
                return Http404("List does not exist")
            items_list=TodoItem.objects.filter(todo_list=todo_list)

            obj=TodoItem.objects.get(id=item_id)
            todoitem=request.POST.get("item")
            if(todoitem==""):
                return HttpResponse("Error: List name cannot be blank")
            
            todochecked=bool(request.POST.get("check",False))
            time=request.POST.get("time")
            date=request.POST.get("date")
            if(time!=''):
                duetime=datetime.datetime.strptime(time,'%H:%M').time()
            else:
                time=obj.due_date.strftime('%H:%M')
                duetime=datetime.datetime.strptime(time,'%H:%M').time()
            if(date!=''):
                duedate=datetime.datetime.strptime(date,'%Y-%m-%d').date()
            else:
                date=obj.due_date.strftime('%Y-%m-%d')
                duedate=datetime.datetime.strptime(date,'%Y-%m-%d').date()
            due_date=datetime.datetime.combine(duedate,duetime)

            TodoItem.objects.filter(id=item_id).update(title=todoitem,checked=todochecked,due_date=due_date,todo_list=t)
        except IntegrityError:
            return HttpResponse("Error: item name already exists under the selected list")
        

    elif 'delete' in request.POST:
        todoitem=TodoItem.objects.get(id=item_id)
        todoitem.delete()

        todo_list = int(request.POST.get("todolist"))
        try:
            t=TodoList.objects.get(id=todo_list)
            items_list=TodoItem.objects.filter(todo_list=todo_list)
        except:
            return HttpResponse("List name not given")
        
    context = {
        'todolist': t,
        'items_list':items_list,
    }
    return redirect("/todo/"+str(list_id))

todo/templates/todo/createitem.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'todo:item_create' %}" method="POST">
        {% csrf_token %}
        <fieldset>

            <h1>Create New Item</h1>
            Item name: <input type="text" name="item" id="item">
            <br><br>
            Checked: <input type="checkbox" name="check" id="check" value=True><br><br>
            Due Date:
            &nbspTime: <input type="time" name="time" id="time"><br><br>
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            Date: <input type="date" name="date" id="date"><br><br>
            Todo List: <select name="todolist" id="todolist">
                {% for todolist in todolists %}
                    {% if listid == None %}
                    <option value={{todolist.id}}>{{todolist}}</option>
                    {% else %}
                        {% if listid == todolist.id %}
                        <option value={{todolist.id}} selected>{{todolist}}</option>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </select>

            <br><br><br>
            <input type="submit">

        </fieldset>
    </form>
{% endblock %}

todo/templates/todo/createlist.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'todo:list_create' %}" method="POST">
        {% csrf_token %}
        <fieldset>

            <h1>Create New List</h1>
            List name: <input type="text" name="name" id="name">
            <input type="submit">

        </fieldset>
    </form>
{% endblock %}

todo/templates/todo/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{todolist.title}}</h1>

    <form action="{% url 'todo:list_details' todolist.id %}" method="POST">
        {% csrf_token %}
        <fieldset>

            <h1>{{todolist.list_name}}</h1><br>

            List name: <input type="text" name="name" id="name" value={{todolist.list_name}}>
            <br><br>

            List items:<br><br>
            <table>
                <th>
                {% for item in items_list %}
                <br>
            
                <tr>
                    {% if item.checked == True %}
                        <a href="/todo/{{todolist.id}}/{{item.id}}/">{{item.title}}</a>
                        &nbsp:&nbspChecked,&nbsp{{item.due_date}}
                    {% else %}
                        <a href="/todo/{{todolist.id}}/{{item.id}}/">{{item.title}}</a>
                        &nbsp:&nbspNot&nbspChecked,&nbsp{{item.due_date}}
                    {% endif %}
                </tr>
            
                {% endfor %}
                </th>
            </table>

            <a href="createitem/" >Add item</a>

            <br><br><br>
            <input type="submit" name="update" value="Update">
            <input type="submit" name="delete" value="Delete">

        </fieldset>
    </form>
{% endblock %}

todo/templates/todo/index.html
{% extends 'base.html' %}

{% block content %}
    <h2>Lists: </h2>
    {% if todolists %}

        
        <table>
            {% for todolist in todolists %}
            <tr>
                <th><a href="/todo/{{todolist.id}}">{{todolist.list_name}}</a></th>
            {% endfor %}
        </table>
    {% endif %}

    <br>
    <a href="/todo/createlist/">Add list</a>
{% endblock %}

todo/templates/todo/item.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{todoitem.title}}</h2>

    <form action="{% url 'todo:item_details' todolist.id todoitem.id %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <br>
            Item name: <input type="text" name="item" id="item" value={{todoitem.title}}>
            </script>
            <br><br>
            {% if todoitem.checked == True %}
            Checked: <input type="checkbox" name="check" id="check" value=True checked><br><br>
            {% else %}
            Checked: <input type="checkbox" name="check" id="check" value=True><br><br>
            {% endif %}
            Due Date:&nbsp{{todoitem.due_date}}<br><br>
            Time:&nbsp<input type="time" name="time" id="time"><br><br>
            Date:&nbsp<input type="date" name="date" id="date"><br><br>
            Todo List: <select name="todolist" id="todolist">
                {% for todo_list in todolists %}
                    {% if todo_list.id == todolist.id %}
                    <option value={{todo_list.id}} selected>{{todo_list}}</option>
                    {% else %}
                    <option value={{todo_list.id}}>{{todo_list}}</option>
                    {% endif %}
                {% endfor %}
            </select>

            <br><br><br>
            <input type="submit" name="update" value="Update">
            &nbsp;
            <input type="submit" name="delete" value="Delete">

        </fieldset>
    </form>
{% endblock %}

todo/templates/todo/view.html
{% extends 'base.html' %}

{% block content %}
    {% if todolists %}

    <ul>
        {% for todolist in todolists %}
        <li>
            {{todolist.list_name}}
            <ul>
            {% for item in todoitems %}
            {% if item.todo_list.id == todolist.id %}
            <li>
                {% if item.checked == True %}
                    <strike>
                        {{item.title}}&nbsp:&nbsp{{item.due_date}}
                    </strike>
                {% else %}
                    <p>{{item.title}}&nbsp:&nbsp{{item.due_date}}</p>
                {% endif %}             
            </li>
            {% endif %}
            {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>

    {% endif %}
{% endblock %}